name: Pull Repo Updates

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:

jobs:
  pull-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pytz

    - name: Run pull_raw_files script
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: python repo_raw_data/pull_raw_files.py

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'cocopuff2u'
        git config --global user.email 'cocopuff2u@yahoo.com'
        git add .
        git commit -m 'Automated update of raw files'
        git push https://github-actions:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/cocopuff2u/mofa_website.git