name: Update Readmes

on:
  schedule:
    - cron: '30 */4 * * *'  # Runs every 4 hours and 30 minutes
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz

    - name: Run update scripts
      run: |
        python update_readme_scripts/update_standalone_update_history_readme.py
        python update_readme_scripts/update_standalone_sha256_readme.py
        python update_readme_scripts/update_standalone_sha1_readme.py
        python update_readme_scripts/update_standalone_cve_history_readme.py
        python update_readme_scripts/update_standalone_current_version_readme.py
        python update_readme_scripts/update_macos_appstore_current_version_readme.py
        python update_readme_scripts/update_ios_appstore_current_version_readme.py

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
          git config --global user.name 'cocopuff2u'
          git config --global user.email 'cocopuff2u@yahoo.com'
        git add docs/*.md
        git commit -m 'Automated update of README files'
        git push https://github-actions:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/cocopuff2u/mofa_website.git